version: '3.8'

services:

  nginx:
    container_name: ${NAMESPACE}_nginx
    image: nginx:${NGINX_VERSION}
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    environment:
      SHOPURI: ${SHOPURI}
      TZ: ${TZ}
    command: '/usr/sbin/nginx -g "daemon off; error_log /dev/stderr info;"'
    networks:
      default:
        aliases:
          - ${SHOPURI}
    volumes:
      - ../magento:/var/www/html:delegated
      - .docker/nginx/ssl:/etc/nginx/ssl:ro
      - .docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - .docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
#    build:
#      context: ./.docker/php
#      args:
#        PHP_VERSION_SET: ${PHP_VERSION_SET}
    container_name: ${NAMESPACE}_php
    image: osioaliu/php:${PHP_VERSION_SET}
    sysctls:
      net.core.somaxconn: 65536
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      COMPOSER_CACHE_DIR: /home/www-data/.composer
      PHP_IDE_CONFIG: "serverName=localhost"
    user: ${UID_GID}
    restart: on-failure
    entrypoint: [ "fixuid","docker-php-entrypoint" ]
    command: [ "php-fpm" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../magento:/var/www/html:delegated
      - ../.composer:/home/www-data/.composer:delegated
      - db_socket:/var/run/mysqld
      - redis_socket:/run/redis/
      - ${HOME}/.ssh:/home/www-data/.ssh:delegated
      - .docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - .docker/php/config/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini:ro
      - .docker/php/config/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro

  elasticsearch:
#    build:
#      context: ./.docker/elasticsearch
#      args:
#        ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION}
    container_name: ${NAMESPACE}_elasticsearch
    image: osioaliu/elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - TZ=${TZ}
      - include_type_name=true
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type:single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      db:
        condition: service_healthy
    entrypoint: 'docker-entrypoint.sh'

  db:
    container_name: ${NAMESPACE}_db
    image: mariadb:${MARIADB_VERSION}
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    healthcheck:
      test: 'mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql/
      - .docker/mysql/db_dumps:/docker-entrypoint-initdb.d
      - .docker/mysql/config/my.cnf:/etc/mysql/my.cnf

  redis:
    container_name: ${NAMESPACE}_redis
    image: redis:${REDIS_VERSION}
    sysctls:
      net.core.somaxconn: '1024'
    entrypoint: redis-server
    command: [ "/etc/redis/redis.conf", "--appendonly", "yes" ]
    environment:
      TZ: ${TZ}
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./.docker/redis/config/redis.conf:/etc/redis/redis.conf:ro

#  rabbitmq:
#    container_name: ${NAMESPACE}_rabbitmq
#    image: rabbitmq:${RABBITMQ_VERSION}
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin2017
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq

#  mailhog:
#    container_name: ${NAMESPACE}_mailhog
#    image: mailhog/mailhog:${MAILHOG_VERSION}
#    environment:
#      TZ: ${TZ}
#    ports:
#      - ${MAILHOG_EXTERNAL_PORT}:8025

#  watchtower:
#    container_name: ${NAMESPACE}_watchtower
#    image: containrrr/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      TZ: ${TZ}
#    command: --interval 3600

#  varnish:
#    container_name: ${NAMESPACE}_varnish
#    image: varnish:${VARNISH_VERSION}
#    environment:
#      - TZ=${TZ}
#      - VARNISH_SIZE=1G
#    tmpfs:
#      - /var/lib/varnish:exec
#    command: "-p default_keep=300"
#    depends_on:
#      - nginx
#    ports:
#      - "80:80"
#    volumes:
#      - .docker/varnish/config/default.vcl:/etc/varnish/default.vcl

volumes:
  db_data: