version: '3.8'

services:

  main:
    container_name: magento2docker_main
    image: osioaliu/magento2docker:dev
    sysctls:
      net.core.somaxconn: 65536
    user: 1000:1000
    volumes:
      - ${PWD}/htdocs/app:/var/www/html/app:delegated
      - ${PWD}/htdocs/dev:/var/www/html/dev:delegated
      - ${PWD}/htdocs/pub:/var/www/html/pub:delegated
      - ${PWD}/htdocs/composer.json:/var/www/html/composer.json:delegated
      - ~/$USER/.composer:/home/www-data/.composer

#  rabbitmq:
#    container_name: ${NAMESPACE}_rabbitmq
#    image: rabbitmq:${RABBITMQ_VERSION}
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin20173
#    ports:
#      - "15672:15672"
#      - "5672:5672"7

#  mailhog:
#    container_name: ${NAMESPACE}_mailhog
#    image: mailhog/mailhog:${MAILHOG_VERSION}
#    ports:
#      - "8025:8025"

#  watchtower:
#    container_name: ${NAMESPACE}_watchtower
#    image: containrrr/watchtower:${WATCHTOWER_VERSION}
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 3600