#!/bin/bash

set -e

. /usr/local/bin/.env


if [[ ! -f /usr/local/bin/mysqltuner.pl ]]; then
  cd /usr/local/bin
  apk add --no-cache perl-doc
  wget http://mysqltuner.pl/ -O /usr/local/bin/mysqltuner.pl
  curl "https://codeload.github.com/FromDual/mariadb-sys/zip/master" >mariadb-sys.zip
  unzip mariadb-sys.zip
  cd mariadb-sys-master/
  mysql -u root -p"$MYSQL_ROOT_PASSWORD" <./sys_10.sql
  chmod +x /usr/local/bin/mysqltuner.pl
fi

/usr/local/bin/mysqltuner.pl --user root --pass "$MYSQL_ROOT_PASSWORD"
