#!/bin/bash

set -e

. .env

xdebugSetup() {
  sudo apk --no-cache add autoconf g++ make linux-headers &&
    sudo pecl install xdebug &&
    sudo -E docker-php-ext-enable xdebug &&
    sudo rm -rf /tmp/pear &&
    sudo apk del --purge autoconf g++ make linux-headers
}

xdebugComfig() {
  mkdir -p /usr/local/etc/php/conf.d/
  VAR=$(
    cat <<'END_HEREDOC'
# xdebug.mode=debug,develop,trace,coverage,profile
xdebug.mode=debug,develop
xdebug.cli_color=1
xdebug.collect_assignments=1
xdebug.collect_params=1
xdebug.max_nesting_level=512
xdebug.remote_handler=dbgp
xdebug.client_port=9003
xdebug.profiler_output_dir=/usr/src/app
xdebug.start_with_request=trigger
xdebug.idekey=magento2docker
xdebug.discover_client_host=yes
END_HEREDOC
  )

  echo "$VAR" | sudo tee -a "/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
}

xdebugComfig
xdebugSetup